ALTER TABLE fl_search ADD COLUMN IF NOT EXISTS stat_start_time TIMESTAMP NULL;
ALTER TABLE fl_search ADD COLUMN IF NOT EXISTS stat_end_time TIMESTAMP NULL;
ALTER TABLE fl_search ADD COLUMN IF NOT EXISTS stat_success BOOLEAN NULL;
ALTER TABLE fl_search ADD COLUMN IF NOT EXISTS stat_error_description VARCHAR(8000) NULL;

